name: imagineer
description: Weblog of Praseetha KR including notes on development, design & other thoughts.
keywords: Web, Development, Design

url: https://imagineer.in
author: Praseetha KR
twitter_username: void_imagineer
github_username: Praseetha-KR

source: src
destination: dev

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

highlighter: rouge

future: true

paginate: 50
paginate_path: "/blog/page:num"
permalink: /blog/:title/

plugins: [jekyll-paginate]

collections:
    works:
        output: true
        order:
            - metarefresh/2014/index.html
            - eventifier/legacy/index.html
            - flutterclock/index.html
            - pothi/index.html
            - metarefresh/2013/index.html
            - rootconf/2014/index.html
            - droidcon/2014/index.html
            - jsfoo/2014/index.html
            - droidcon/2013/index.html
            - pythonexpress/index.html
            - bangpypers/index.html
            - pssi/index.html
            - droidcon/2012/index.html
            - gitworkshop/index.html
            - certificate/index.html
            - aser/index.html
