name: imagineer
description: Weblog of Praseetha KR including notes on development, design & other thoughts.
keywords: Web, Development, Design

url: http://imagineer.in
author: Praseetha KR
twitter_username: void_imagineer
github_username: Praseetha-KR

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

highlighter: rouge

paginate: 6
paginate_path: "/blog/page:num"
permalink: /blog/:title/

gems: [jekyll-paginate]
