name: imagineer
description: Weblog of Praseetha KR including notes on development, design & other thoughts.
keywords: Web, Development, Design

url: https://imagineer.in
author: Praseetha KR
twitter_username: void_imagineer
github_username: Praseetha-KR

source: src
destination: dev

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

highlighter: rouge

future: true

paginate: 50
paginate_path: "/blog/page:num"
permalink: /blog/:title/

plugins: [jekyll-paginate]

collections:
    works:
        output: true
        order:
            - metarefresh/2014.html
            - eventifier/legacy.html
            - flutterclock.html
            - rootconf/2014.html
            - eventifier.html
            - pothi.html
            - pythonexpress.html
            - jsfoo/2014.html
            - metarefresh/2013.html
            - droidcon/2014.html
            - motogarage.html
            - droidcon/2013.html
            - bangpypers.html
            - pssi.html
            - droidcon/2012.html
            - gitworkshop.html
            - certificate.html
            - aser.html
