name: imagineer
blurb: 'coding with colors'
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
paginate: 12
paginate_path: "/page:num"
permalink: /blog/:title
