name: imagineer
description: Weblog of Praseetha KR including notes on development, design & other thoughts.
keywords: Web, Development, Design
author: Praseetha KR
url: http://imagineer.in
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
paginate: 12
paginate_path: "/page:num"
permalink: /blog/:title
twitter_username: void_imagineer
# relative_permalinks: true
future: true
