name: imagineer
description: Weblog of Praseetha KR including notes on development, design & other thoughts.
keywords: Web, Development, Design
author: Praseetha KR
url: http://imagineer.in
twitter_username: void_imagineer

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge
# redcarpet:
#     extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge

# future: true

paginate: 6
paginate_path: "/page:num"
permalink: /blog/:title/

# relative_permalinks: true


gems: [jekyll-paginate]
